<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/*
 * Implements hook_menu()
 */

function luggage_ux_menu() {
  $items = array();

  $items['admin/config/user-interface/luggage_ux'] = array(
    'title' => 'Luggage UX',
    'description' => 'Configuration for the Luggage UX module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('luggage_ux_form'),
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function luggage_ux_form($form, &$form_state) {
//  $form['luggage_ux_block_collapse_enabled'] = array(
//    '#type' => 'checkbox',
//    '#title' => t('Block Collapsed enabled'),
//    '#description' => t('Enables/disables the block collapse add-on'),
//    '#default_value' => variable_get('luggage_ux_block_collapse_enabled', 'Block Collapse Enabled'),
//  );
//
//  $form['luggage_ux_block_filter_enabled'] = array(
//    '#type' => 'checkbox',
//    '#title' => t('Block Filter enabled'),
//    '#description' => t('Enables/disables the block filter add-on'),
//    '#default_value' => variable_get('luggage_ux_block_filter_enabled', 'Block Filter Enabled'),
//  );

  $form['luggage_ux_tag_box_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Tag Box enabled'),
    '#description' => t('Enables/disables the tag box add-on'),
    '#default_value' => variable_get('luggage_ux_tag_box_enabled', 'Tag Box Enabled'),
  );

  return system_settings_form($form);
}

function luggage_ux_preprocess_block(&$variables) {
  if($variables) {
    if(variable_get('luggage_ux_block_filter_block_'.$variables['block']->delta.'_enabled',Null)) {
      $variables['classes_array'][] = 'luggage_ux_block_filter';
      _attach_block_filter();
    }
    if(variable_get('luggage_ux_block_collapse_block_'.$variables['block']->delta.'_enabled',Null)) {
      $variables['classes_array'][] = 'luggage_ux_block_collapse';
      _attach_block_collapse();
    }
  }
}

function luggage_ux_form_alter(&$form, &$form_state, $form_id) {
  if(variable_get('luggage_ux_tag_box_enabled', Null)) {
    _attach_tag_box();
  }
}

function luggage_ux_form_block_admin_configure_alter(&$form, &$form_state) {
  if($form) {
    $form['luggage_ux_block_filter'] = array(
      '#type' => 'fieldset',
      '#title' => t('Block Filter Add-on'),
      '#collapsible' => false,
      '#description' => t('Enable/disable the block filter add-on, which adds a filter input box to the block.'),
      'block_filter_enabled' => array(
        '#type' => 'checkbox',
        '#title' => t('Enabled'),
        '#default_value' => variable_get('luggage_ux_block_filter_block_' . $form['delta']['#value'] . '_enabled', 'Block Filter ' . $form['delta']['#value'] . ' Enabled'),
      ),
    );

    $form['luggage_ux__block_collapse'] = array(
      '#type' => 'fieldset',
      '#title' => t('Block Collapse Add-on'),
      '#collapsible' => false,
      '#description' => t('Enable/disable the block collapse add-on, which gives the user the ability to treat a block as a clickable drop-down menu.'),
      'block_collapse_enabled' => array(
        '#type' => 'checkbox',
        '#title' => t('Enabled'),
        '#default_value' => variable_get('luggage_ux_block_collapse_block_' . $form['delta']['#value'] . '_enabled', 'Block Collapse ' . $form['delta']['#value'] . ' Enabled'),
      ),
    );

    $form['#submit'][] = '_luggage_ux_form_block_admin_configure_submit';
  }
}

function _luggage_ux_form_block_admin_configure_submit($form, &$form_state) {
  if($form_state) {
    variable_set('luggage_ux_block_filter_block_' . $form_state['build_info']['args'][1] . '_enabled', $form_state['values']['block_filter_enabled']);
    variable_set('luggage_ux_block_collapse_block_' . $form_state['build_info']['args'][1] . '_enabled', $form_state['values']['block_collapse_enabled']);
  }
}

function _attach_tag_box() {
  drupal_add_js(drupal_get_path('module', 'luggage_ux') . '/js/tag_box.js');
  drupal_add_css(drupal_get_path('module', 'luggage_ux') . '/css/tag_box.css');
}

function _attach_block_collapse() {
  drupal_add_js(drupal_get_path('module', 'luggage_ux') . '/js/block_collapse.js');
  drupal_add_css(drupal_get_path('module', 'luggage_ux') . '/css/block_collapse.css');
}

function _attach_block_filter() {
  drupal_add_js(drupal_get_path('module', 'luggage_ux') . '/js/block_filter.js');
  drupal_add_css(drupal_get_path('module', 'luggage_ux') . '/css/block_filter.css');
}